title: Fala PB
theme: jekyll-theme-slate
markdown: kramdown
baseurl: "/fala_pb"
exp_nav:
  first: 1
  last: 25
exclude:
  - amostras/montar_manifesto.py
  - amostras/gerar_pagina.py
  - amostras/README.md